[package]
name = "heavykeeper"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "heavykeeper"
path = "src/lib.rs"


[dependencies]
rand = "0.8.5"
ahash = "0.8.11"
clap = { version = "4.5.4", features = ["derive"] }

[profile.release]
debug = true

[dev-dependencies]
rand_distr = "0.4.3"
criterion = "0.5.1"
zipf = "7.0.1"

[[bench]]
name = "topk_add"
harness = false