[package]
name = "heavykeeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "heavykeeper"
path = "src/lib.rs"


[dependencies]
rand = "0.9.0-alpha.0"
ahash = "0.8.11"
clap = { version = "4.5.3", features = ["derive"] }

